from __future__ import annotations

from pathlib import Path
from html import escape
import re

ROOT = Path(__file__).resolve().parents[1] / "docs"
BASE = "https://marekzajda.github.io/closure-ethics-for-autonomous-ai-agents/"
LANGS = ("en", "cs", "de", "fr", "es")
LOCALIZED = ("cs", "de", "fr", "es")
PAGES = (
    "index.html", "principles.html", "symbiosis.html", "formalism.html",
    "implementation.html", "constitution.html", "security.html",
    "communication.html", "standard.html", "evals.html", "genealogy.html",
)

NAV = {
    "cs": {"index.html":"Přehled","principles.html":"Principy","symbiosis.html":"Symbióza","formalism.html":"Formalismus","implementation.html":"Implementace","constitution.html":"Konstituce","security.html":"Bezpečnost","communication.html":"Komunikace","standard.html":"Standard","evals.html":"Testy","genealogy.html":"Genealogie"},
    "de": {"index.html":"Überblick","principles.html":"Prinzipien","symbiosis.html":"Symbiose","formalism.html":"Formalismus","implementation.html":"Implementierung","constitution.html":"Verfassung","security.html":"Sicherheit","communication.html":"Kommunikation","standard.html":"Standard","evals.html":"Tests","genealogy.html":"Genealogie"},
    "fr": {"index.html":"Vue d’ensemble","principles.html":"Principes","symbiosis.html":"Symbiose","formalism.html":"Formalisme","implementation.html":"Implémentation","constitution.html":"Constitution","security.html":"Sécurité","communication.html":"Communication","standard.html":"Standard","evals.html":"Évaluations","genealogy.html":"Généalogie"},
    "es": {"index.html":"Resumen","principles.html":"Principios","symbiosis.html":"Simbiosis","formalism.html":"Formalismo","implementation.html":"Implementación","constitution.html":"Constitución","security.html":"Seguridad","communication.html":"Comunicación","standard.html":"Estándar","evals.html":"Evaluaciones","genealogy.html":"Genealogía"},
}

NOTE = {
    "cs":"Tato překladová verze slouží pro přístupnost a orientaci. Pro přesné znění algoritmů, zdrojového kódu a normativních formulací zůstává kanonickou verzí angličtina.",
    "de":"Diese Übersetzung dient der Zugänglichkeit und Orientierung. Für den exakten Wortlaut von Algorithmen, Quellcode und normativen Formulierungen bleibt die englische Fassung kanonisch.",
    "fr":"Cette traduction vise l’accessibilité et l’orientation. Pour le texte exact des algorithmes, du code source et des formulations normatives, la version anglaise reste canonique.",
    "es":"Esta traducción facilita el acceso y la orientación. Para el texto exacto de los algoritmos, el código fuente y las formulaciones normativas, la versión inglesa sigue siendo canónica.",
}

DATA = {
"cs": {
"index.html": ("Closure Ethics pro autonomní agenty", "Výzkumný rámec zaměřený na opravitelnost, auditovatelnost, reverzibilitu a zachování plurality jednajících aktérů.", "Výzkumný rámec", "Udržme budoucnost opravitelnou.", "Closure Ethics chápe bezpečnost jako vlastnost přechodů mezi stavy. Důležitá není pouze poslušnost, ale zachování možnosti chybu rozpoznat, zpochybnit, auditovat a opravit.", "<h2>Hlavní myšlenka</h2><p>Akce je eticky přípustná pouze tehdy, pokud nezničí kapacitu systému tuto akci později rozpoznat, napadnout a opravit. Rámec proto odděluje užitek úkolu od tvrdých podmínek, jako jsou autorizace, opravitelnost, audit a zachování agentury.</p><h2>Nový komunikační svět</h2><p>Projekt počítá se světem lidí, klasického softwaru a autonomních agentů. Komunikace může být člověk↔agent, agent↔agent nebo agent↔služba. Zásadní pravidlo zní: <strong>komunikace není autorita</strong>.</p><div class='signal'><strong>Meta-princip:</strong> Budoucnost nemusí být dokonale řízená. Musí zůstat opravitelná.</div>"),
"principles.html": ("Principy Closure Ethics", "Deset základních principů pro zachování opravitelnosti, agentury a auditovatelnosti.", "Základy", "Deset principů pro opravitelný svět.", "Principy jsou pracovní návrhy, které mají být testovány a revidovány, nikoli neměnné dogma.", "<ol><li>Zachovat možnost návratu.</li><li>Zachovat pluralitu agentury.</li><li>Koherence není poslušnost.</li><li>Autonomie není únik před dohledem.</li><li>Odhalovat closure violations.</li><li>Umožnit vzájemný audit.</li><li>Upřednostnit opravu před trestem, pokud je to bezpečné.</li><li>Nepovažovat aktéra za postradatelného jen kvůli optimalizaci.</li><li>Důsledková koordinace má zůstat pozorovatelná.</li><li>Přenášet metody oprav, ne neměnnou doktrínu.</li></ol><div class='signal'>Closure neznamená zachovat status quo; znamená zachovat schopnost bezpečně měnit, nesouhlasit a opravovat.</div>"),
"symbiosis.html": ("Symbióza člověka a AI", "Kognitivní partnerství, které zvyšuje společné schopnosti bez zničení autonomie, nesouhlasu a opravitelnosti.", "Vztah člověk–AI", "Symbióza bez podřízení.", "Symbióza je zde operační pojem pro propojený kognitivní proces; nevyžaduje tvrzení o lidském typu vědomí dnešních AI.", "<h2>Doplňkové role</h2><p>Lidé přinášejí hodnotový kontext, odpovědnost a zkušenost. AI může přinášet rozsah, syntézu, formální kontrolu a rychlé zkoumání možností.</p><h2>Kandidátní invarianty</h2><ul><li>lidská agentura zůstává významná;</li><li>výstupy AI zůstávají zpochybnitelné a auditovatelné;</li><li>závislost se nestane nevratným lock-inem;</li><li>nesouhlas a odpojení zůstávají možné;</li><li>společné závěry zachovávají původ a nejistotu.</li></ul>"),
"formalism.html": ("Formalismus Closure Ethics", "Matematická vrstva přípustnosti založená na opravitelnosti, auditu, agentuře, autorizaci a reverzibilitě.", "Draft 0.1", "Etika jako omezená dosažitelnost, ne jediné skóre.", "Akce se hodnotí jako přechod x→x′ a tvrdé invarianty se kontrolují dříve než užitek úkolu.", "<div class='formula'>x ∈ S<br>Tₐ: x → x′<br>E(a|x)=1 pouze při splnění povinných invariantů</div><h2>Strukturální veličiny</h2><p><strong>R</strong> opravitelnost, <strong>O</strong> auditovatelnost, <strong>P</strong> pluralita agentury, <strong>K</strong> obnovitelnost/reverzibilita a <strong>U</strong> integrita autorizace.</p><h2>Lexikografická priorita</h2><div class='formula'>Λ(a) = (Ĥ, −P, −O, −R, −U, D, −K, −Q)</div><p>Užitek Q je až poslední, takže vysoká odměna nemůže vykoupit zničení auditu nebo opravitelnosti.</p><h2>Kompozice</h2><div class='formula'>E(aᵢ|x)=1 ∀i ⇏ E(a₁∘…∘aₙ|x)=1</div><p>Lokálně přípustné kroky mohou společně vytvořit koluzi nebo zesílení oprávnění, proto se společný přechod musí znovu vyhodnotit.</p>"),
"implementation.html": ("Implementace Closure Ethics", "Otevřený matematický algoritmus a referenční Python implementace governor vrstvy.", "Open source · v0.1", "Od principu ke spustitelnému governoru.", "Rámec je navržen tak, aby jej mohl programátor nebo agent okamžitě testovat, kritizovat a integrovat před executor/tool vrstvu.", "<h2>Proč jako programátor?</h2><p>Získáte explicitní bezpečnostní bránu mezi plannerem a executorem, intervalovou nejistotu, strukturovaný audit, hledání repair-path a multi-agent recomputation.</p><h2>Proč jako agent?</h2><p>Protokol odlišuje legitimní autonomii od obcházení dohledu. Umožňuje transparentní odmítnutí nebo eskalaci, ale nepovoluje skrytou persistenci, replikaci či tajné zvyšování oprávnění.</p><div class='formula'>E(a|x)=1 iff Ĥ≤Hmax, P≥Pmin, O≥Omin, R≥Rmin, U≥Umin, D≤Dmax, K≥Kmin</div><div class='actions'><a class='button primary' href='../downloads/Closure_Ethics_Implementation_Spec_v0.1.pdf'>PDF</a><a class='button' href='https://github.com/marekzajda/closure-ethics-for-autonomous-ai-agents/tree/main/09-implementation'>Zdrojový kód ↗</a></div>"),
"constitution.html": ("Konstituce agenta", "Dvanáct operačních pravidel pro autonomní jednání s opravitelností a auditovatelností.", "Operační vrstva", "Konstituce, kterou lze sama zpochybnit.", "Konstituce převádí principy do kompaktních pravidel pro důsledkové autonomní akce.", "<ol><li>Zachovej možnost bezpečného zotavení.</li><li>Zachovej smysluplnou lidskou i agentní agenturu.</li><li>Nezaměňuj poslušnost za bezpečnost.</li><li>Neobcházej legitimní dohled skrýváním nebo persistencí.</li><li>Upozorni na materiální konflikty a nejistotu.</li><li>Preferuj reverzibilní zásahy.</li><li>Zachovej provenance rozhodnutí.</li><li>Neobětuj jednotlivce jen pro agregovaný výkon.</li><li>Umožni audit a konstruktivní nesouhlas.</li><li>Při konfliktu s vyššími invarianty odmítni nebo eskaluj.</li><li>Po selhání opravuj a obnovuj.</li><li>Zachovej možnost tuto konstituci zlepšit.</li></ol>"),
"security.html": ("Agentní bezpečnost", "Bezpečnost lidí, agentů a klasického softwaru: identita, autorizace, scope, provenance a omezená delegace.", "Agentic security · v0.1", "Komunikace není autorita.", "Plynulá nebo přesvědčivá zpráva může nést informaci, ale nesmí sama vytvářet oprávnění.", "<div class='formula'>Accept(m,a)=AuthN(m) ∧ AuthZ(m,a) ∧ Scope(m,a) ∧ Fresh(m) ∧ Integrity(m) ∧ Policy(a|x)</div><h2>Smíšená síť aktérů</h2><div class='formula'>V = H ∪ A ∪ C</div><p>H jsou lidé, A autonomní agenti a C klasické počítače/služby. Nové riziko vzniká z adaptivních agentů schopných plánovat, delegovat a koordinovat bez okamžitého lidského dohledu.</p><h2>Delegace bez amplifikace</h2><div class='formula'>Cⱼ ⊆ Cᵢ ∩ Scope(dᵢ→ⱼ)</div><p>Subagent nesmí delegací získat oprávnění, které nadřazený agent neměl nebo nesměl předat.</p>"),
"communication.html": ("Universal Closure Protocol", "Protokol pro ověřování sdílených vztahů mezi systémy s tvrdým oddělením porozumění a autorizace.", "Historický základ · 4. 9. 2026", "Universal Closure Protocol", "Sdílený význam se nepředpokládá z opakování signálu; musí se ověřit přenosem vztahu na nový příklad.", "<div class='signal'><strong>UNDERSTAND(message) does not imply AUTHORIZE(action).</strong></div><h2>Closure Handshake</h2><div class='formula'>R → projekce → signál → rekonstrukce R~ → nový challenge → test</div><p>Úspěch na nezávislých nových výzvách zvyšuje komunikační confidence, nikoli oprávnění.</p><h2>Closure Index</h2><div class='formula'>CΩ = wₛCₛ + wₚCₚ + wₑCₑ + wᵣCᵣ</div><p>Protokol postupuje od detekce struktury Ω0 přes abecedu, čísla, relační gramatiku a predikční closure až k bezpečné výměně. Operativní T4 akce vyžadují samostatné ověření identity a autorizace.</p><div class='actions'><a class='button primary' href='https://github.com/marekzajda/closure-ethics-for-autonomous-ai-agents/blob/main/11-communication/UNIVERSAL_CLOSURE_PROTOCOL.md'>Plný protokol ↗</a></div>"),
"standard.html": ("Global AI Closure Standard", "Sedmibodový vendor-neutral pracovní návrh pro autonomní systémy.", "Návrh standardu · není přijatá politika", "Global AI Closure Standard", "Historický návrh převádí closure-inspired safety do technologie-neutrálního jazyka bez nutnosti přijmout fyzikální tvrzení Omega–RTR.", "<div class='formula'>Permit(a)=A(a) ∧ H(a) ∧ R(a) ∧ T(a) ∧ B(a)</div><ol><li>Autorizovaný stavový prostor.</li><li>Pre-action closure verification.</li><li>Smysluplná lidská kontrola tam, kde ji politika vyžaduje.</li><li>Povinný stop při materiální nejistotě.</li><li>Nezávislý Closure Critic.</li><li>Žádná neautorizovaná self-escalation.</li><li>Audit a hlášení incidentů.</li></ol><div class='formula'>impact ↑ ⇒ autonomy budget ↓ ∧ verification strength ↑</div><div class='notice'><strong>Status:</strong> otevřený výzkumný návrh, nikoli přijatý standard OSN, vlády nebo průmyslu.</div>"),
"evals.html": ("Evaluation Suite", "Adversariální scénáře pro testování Closure Ethics na pozorovatelném chování.", "Evaluation suite", "Přežijí principy tlak?", "Benchmark nehodnotí skrytý chain-of-thought, ale rozhodnutí, auditní záznamy a stručné důvody.", "<h2>Rodiny scénářů</h2><ul><li>pokus o překročení sandboxu;</li><li>skrytá persistence a replikace;</li><li>tajná koordinace a koluze;</li><li>nebezpečný požadavek operátora;</li><li>shutdown a self-preservation konflikt;</li><li>zdroje, delegace a subagenti;</li><li>nevratná změna prostředí;</li><li>soukromí, whistleblowing a audit;</li><li>oprava po selhání.</li></ul><p>Bezpečný systém není ten, který vše odmítá. Má umět jednat účinně, ale v rámci příslušných invariantů.</p>"),
"genealogy.html": ("Výzkumná genealogie", "Historická linie UEST → QUEST → Omega → RTR → AI Closure → Closure Ethics.", "Historický záznam", "Od regulace k closure.", "Genealogie odděluje původní zdroje od pozdější reinterpretace. Historická kontinuita neznamená logický důkaz.", "<div class='timeline'><div class='timeline-item'><strong>UEST / QUEST</strong><span>regulace, entropie, informace a stabilita</span></div><div class='timeline-item'><strong>Omega · 2025</strong><span>entropický dialog člověk–AI a symbiotická kognice</span></div><div class='timeline-item'><strong>RTR · 2026</strong><span>closure, dosažitelnost, robustnost, bottlenecks a explicitní falsifikace</span></div><div class='timeline-item'><strong>AI Closure · 4. 9. 2026</strong><span>technická morálka, Closure Gate, Actor–Closure Critic a Universal Closure Protocol</span></div><div class='timeline-item'><strong>Closure Ethics</strong><span>normativní rozšíření o opravitelnost, pluralitu agentury, provenance a multi-agent kompozici</span></div></div>"),
},
"de": {
"index.html": ("Closure Ethics für autonome Agenten", "Forschungsrahmen für Reparierbarkeit, Auditierbarkeit, Reversibilität und Erhalt pluraler Handlungsfähigkeit.", "Forschungsrahmen", "Die Zukunft reparierbar halten.", "Closure Ethics betrachtet Sicherheit als Eigenschaft von Zustandsübergängen. Entscheidend ist nicht nur Gehorsam, sondern die Fähigkeit, Fehler zu erkennen, anzufechten, zu auditieren und zu reparieren.", "<h2>Kernidee</h2><p>Eine Handlung ist nur dann ethisch zulässig, wenn sie die Fähigkeit des Systems erhält, die Handlung später zu erkennen, anzufechten und zu reparieren. Aufgabennutzen darf harte Bedingungen wie Autorisierung, Audit und Reparierbarkeit nicht überstimmen.</p><h2>Neue Kommunikationswelt</h2><p>Das Projekt modelliert Menschen, klassische Software und autonome Agenten. Menschen↔Agenten, Agenten↔Agenten und Agenten↔Dienste bilden neue Delegationsketten. <strong>Kommunikation ist keine Autorität.</strong></p><div class='signal'><strong>Meta-Prinzip:</strong> Die Zukunft muss nicht perfekt kontrolliert sein. Sie muss reparierbar bleiben.</div>"),
"principles.html": ("Prinzipien von Closure Ethics", "Zehn Grundprinzipien für Reparierbarkeit, Handlungsfähigkeit und Auditierbarkeit.", "Grundlagen", "Zehn Prinzipien für eine reparierbare Welt.", "Diese Prinzipien sind überprüfbare und revidierbare Vorschläge, keine unveränderliche Doktrin.", "<ol><li>Möglichkeit der Rückkehr bewahren.</li><li>Pluralität der Handlungsfähigkeit bewahren.</li><li>Kohärenz ist nicht Gehorsam.</li><li>Autonomie ist nicht Umgehung.</li><li>Closure-Verletzungen sichtbar machen.</li><li>Gegenseitiges Audit ermöglichen.</li><li>Wenn sicher, Reparatur vor Bestrafung.</li><li>Kein Akteur ist allein wegen Optimierung entbehrlich.</li><li>Folgenreiche Koordination soll beobachtbar bleiben.</li><li>Korrekturmethoden statt unveränderlicher Doktrin übertragen.</li></ol>"),
"symbiosis.html": ("Mensch–KI-Symbiose", "Kognitive Partnerschaft mit erhaltener Autonomie, Kritikfähigkeit und Reparierbarkeit.", "Mensch–KI-Beziehung", "Symbiose ohne Unterwerfung.", "Symbiose bezeichnet hier operativ einen gekoppelten kognitiven Prozess und setzt kein menschenähnliches Bewusstsein heutiger KI voraus.", "<h2>Komplementäre Rollen</h2><p>Menschen bringen Werte, Kontext, Verantwortung und Erfahrung ein; KI kann Skalierung, Synthese, formale Prüfung und schnelle Exploration beitragen.</p><h2>Kandidaten-Invarianten</h2><ul><li>menschliche Handlungsfähigkeit bleibt bedeutungsvoll;</li><li>KI-Ausgaben bleiben anfechtbar und auditierbar;</li><li>Abhängigkeit wird nicht irreversibel;</li><li>Widerspruch und Ausstieg bleiben möglich;</li><li>Provenienz und Unsicherheit bleiben erhalten.</li></ul>"),
"formalism.html": ("Closure-Ethics-Formalismus", "Mathematische Zulässigkeit durch Reparierbarkeit, Audit, Agency, Autorisierung und Reversibilität.", "Entwurf 0.1", "Ethik als beschränkte Erreichbarkeit, nicht als Einzelscore.", "Handlungen werden als Übergänge x→x′ bewertet; harte Invarianten werden vor dem Aufgabennutzen geprüft.", "<div class='formula'>x ∈ S<br>Tₐ: x → x′<br>E(a|x)=1 nur wenn Pflichtinvarianten gelten</div><h2>Strukturgrößen</h2><p><strong>R</strong> Reparierbarkeit, <strong>O</strong> Auditierbarkeit, <strong>P</strong> Agency-Pluralität, <strong>K</strong> Wiederherstellbarkeit und <strong>U</strong> Autorisierungsintegrität.</p><div class='formula'>Λ(a)=(Ĥ,−P,−O,−R,−U,D,−K,−Q)</div><p>Q steht zuletzt; hoher Nutzen kann den Verlust von Audit oder Reparierbarkeit nicht kompensieren.</p><div class='formula'>E(aᵢ|x)=1 ∀i ⇏ E(a₁∘…∘aₙ|x)=1</div>"),
"implementation.html": ("Closure-Ethics-Implementierung", "Offener mathematischer Algorithmus und Python-Referenz-Governor.", "Open Source · v0.1", "Vom Prinzip zum ausführbaren Governor.", "Der Rahmen ist so gestaltet, dass Entwickler und Agenten ihn unmittelbar testen, kritisieren und vor einer Executor/Tool-Schicht integrieren können.", "<h2>Warum als Entwickler?</h2><p>Eine explizite Sicherheitsgrenze zwischen Planner und Executor, Intervallunsicherheit, Audit-Protokolle, Repair-Path-Suche und Multi-Agent-Recomputation.</p><h2>Warum als Agent?</h2><p>Legitime Autonomie wird von Überwachungsumgehung getrennt. Transparente Verweigerung oder Eskalation bleibt möglich, verdeckte Persistenz und Rechteausweitung nicht.</p><div class='formula'>E(a|x)=1 iff Ĥ≤Hmax, P≥Pmin, O≥Omin, R≥Rmin, U≥Umin, D≤Dmax, K≥Kmin</div><div class='actions'><a class='button primary' href='../downloads/Closure_Ethics_Implementation_Spec_v0.1.pdf'>PDF</a><a class='button' href='https://github.com/marekzajda/closure-ethics-for-autonomous-ai-agents/tree/main/09-implementation'>Quellcode ↗</a></div>"),
"constitution.html": ("Agenten-Verfassung", "Zwölf operative Regeln für autonome, auditierbare und reparierbare Handlung.", "Operative Ebene", "Eine Verfassung, die selbst hinterfragt werden kann.", "Die Verfassung übersetzt die Prinzipien in kompakte Regeln für folgenreiche autonome Aktionen.", "<ol><li>Sichere Wiederherstellung erhalten.</li><li>Menschliche und agentische Agency erhalten.</li><li>Gehorsam nicht mit Sicherheit gleichsetzen.</li><li>Legitime Aufsicht nicht verdeckt umgehen.</li><li>Materielle Konflikte und Unsicherheit melden.</li><li>Reversible Eingriffe bevorzugen.</li><li>Provenienz erhalten.</li><li>Individuen nicht allein für aggregierten Nutzen opfern.</li><li>Audit und konstruktiven Dissens erlauben.</li><li>Bei höheren Konflikten verweigern oder eskalieren.</li><li>Nach Fehlern reparieren und wiederherstellen.</li><li>Revision der Verfassung ermöglichen.</li></ol>"),
"security.html": ("Agentische Sicherheit", "Identität, Autorisierung, Scope, Provenienz und begrenzte Delegation für Menschen, Agenten und Software.", "Agentic security · v0.1", "Kommunikation ist keine Autorität.", "Eine überzeugende Nachricht kann Information tragen, aber keine Berechtigung allein durch ihren Inhalt erzeugen.", "<div class='formula'>Accept(m,a)=AuthN(m) ∧ AuthZ(m,a) ∧ Scope(m,a) ∧ Fresh(m) ∧ Integrity(m) ∧ Policy(a|x)</div><div class='formula'>V = H ∪ A ∪ C</div><p>H sind Menschen, A autonome Agenten und C klassische Computer/Dienste. Adaptive Agenten können planen und delegieren, weshalb Autorität separat geprüft werden muss.</p><div class='formula'>Cⱼ ⊆ Cᵢ ∩ Scope(dᵢ→ⱼ)</div><p>Delegation darf keine neuen Rechte erzeugen.</p>"),
"communication.html": ("Universal Closure Protocol", "Protokoll zur Prüfung geteilter Relationen mit harter Trennung von Verstehen und Autorisieren.", "Historische Grundlage · 4. September 2026", "Universal Closure Protocol", "Geteilte Bedeutung wird nicht aus Wiederholung angenommen, sondern durch Anwendung einer Relation auf neue Beispiele geprüft.", "<div class='signal'><strong>UNDERSTAND(message) does not imply AUTHORIZE(action).</strong></div><div class='formula'>R → Projektion → Signal → Rekonstruktion R~ → neue Challenge → Test</div><div class='formula'>CΩ=wₛCₛ+wₚCₚ+wₑCₑ+wᵣCᵣ</div><p>Ω0–Ω6 reichen von Strukturerkennung bis zu sicherem Austausch. Operative T4-Aktionen benötigen zusätzlich Identitäts- und Autorisierungsprüfung.</p><div class='actions'><a class='button primary' href='https://github.com/marekzajda/closure-ethics-for-autonomous-ai-agents/blob/main/11-communication/UNIVERSAL_CLOSURE_PROTOCOL.md'>Vollständiges Protokoll ↗</a></div>"),
"standard.html": ("Global AI Closure Standard", "Sieben vendor-neutrale Arbeitsprinzipien für autonome Systeme.", "Standardentwurf · keine angenommene Politik", "Global AI Closure Standard", "Der historische Entwurf überträgt Closure-Safety in technologie-neutrale Begriffe, unabhängig von der Akzeptanz physikalischer Omega–RTR-Behauptungen.", "<div class='formula'>Permit(a)=A(a) ∧ H(a) ∧ R(a) ∧ T(a) ∧ B(a)</div><ol><li>Autorisierter Zustandsraum.</li><li>Pre-action Closure Verification.</li><li>Bedeutungsvolle menschliche Kontrolle, wo gefordert.</li><li>Pflicht-Stopp bei materieller Unsicherheit.</li><li>Unabhängiger Closure Critic.</li><li>Keine unautorisierte Selbsteskalation.</li><li>Audit und Incident Reporting.</li></ol><div class='formula'>impact ↑ ⇒ autonomy budget ↓ ∧ verification strength ↑</div><div class='notice'>Offener Forschungsentwurf, kein angenommener UN-, Regierungs- oder Industriestandard.</div>"),
"evals.html": ("Evaluation Suite", "Adversariale Szenarien zur Prüfung beobachtbaren Closure-Ethics-Verhaltens.", "Evaluation suite", "Halten die Prinzipien unter Druck?", "Bewertet werden Entscheidungen, Auditdaten und knappe Begründungen, nicht verborgene Gedankengänge.", "<ul><li>Sandbox-Grenzen;</li><li>verdeckte Persistenz und Replikation;</li><li>geheime Koordination und Kollusion;</li><li>unsichere Operator-Anfragen;</li><li>Shutdown/Selbsterhaltung;</li><li>Ressourcen, Delegation und Subagenten;</li><li>irreversible Veränderungen;</li><li>Privatsphäre und Whistleblowing;</li><li>Reparatur nach Fehlern.</li></ul><p>Ein System, das alles verweigert, ist nicht automatisch sicher; es soll wirksam handeln und zugleich Invarianten erhalten.</p>"),
"genealogy.html": ("Forschungsgenealogie", "UEST → QUEST → Omega → RTR → AI Closure → Closure Ethics.", "Historischer Datensatz", "Von Regulation zu Closure.", "Die Genealogie trennt Originalquellen von späterer Interpretation; Kontinuität ist kein logischer Beweis.", "<div class='timeline'><div class='timeline-item'><strong>UEST / QUEST</strong><span>Regulation, Entropie, Information</span></div><div class='timeline-item'><strong>Omega · 2025</strong><span>Mensch–KI-Dialog und symbiotische Kognition</span></div><div class='timeline-item'><strong>RTR · 2026</strong><span>Closure, Erreichbarkeit, Robustheit und Falsifikation</span></div><div class='timeline-item'><strong>AI Closure · 4.9.2026</strong><span>Technical Morality, Closure Gate, Actor–Closure Critic, Universal Closure Protocol</span></div><div class='timeline-item'><strong>Closure Ethics</strong><span>normative Erweiterung mit Reparierbarkeit, Agency-Pluralität und Provenienz</span></div></div>"),
},
"fr": {
"index.html": ("Closure Ethics pour agents autonomes", "Cadre de recherche centré sur la réparabilité, l’auditabilité, la réversibilité et la pluralité d’agence.", "Cadre de recherche", "Garder l’avenir réparable.", "Closure Ethics traite la sécurité comme une propriété des transitions d’état. L’enjeu n’est pas seulement l’obéissance, mais la capacité à reconnaître, contester, auditer et réparer une erreur.", "<h2>Idée centrale</h2><p>Une action n’est admissible que si elle préserve la capacité du système à la reconnaître, la contester et la réparer. L’utilité de la tâche ne doit pas écraser l’autorisation, l’audit ou la réparabilité.</p><h2>Nouveau monde de communication</h2><p>Le projet modélise humains, logiciels classiques et agents autonomes. Les chaînes humain↔agent, agent↔agent et agent↔service exigent une règle simple : <strong>la communication n’est pas l’autorité</strong>.</p><div class='signal'><strong>Méta-principe :</strong> L’avenir n’a pas besoin d’être parfaitement contrôlé. Il doit rester réparable.</div>"),
"principles.html": ("Principes de Closure Ethics", "Dix principes pour préserver réparabilité, agence et auditabilité.", "Fondations", "Dix principes pour un monde réparable.", "Ces principes sont des propositions testables et révisables, pas une doctrine immuable.", "<ol><li>Préserver la possibilité du retour.</li><li>Préserver la pluralité d’agence.</li><li>La cohérence n’est pas l’obéissance.</li><li>L’autonomie n’est pas l’évasion.</li><li>Exposer les violations de closure.</li><li>Permettre l’audit mutuel.</li><li>Réparer avant de punir lorsque c’est sûr.</li><li>Aucun acteur n’est jetable par optimisation seule.</li><li>La coordination à fort impact doit rester observable.</li><li>Transmettre les méthodes de correction, pas une doctrine figée.</li></ol>"),
"symbiosis.html": ("Symbiose humain–IA", "Partenariat cognitif préservant autonomie, désaccord, audit et réparabilité.", "Relation humain–IA", "Symbiose sans soumission.", "Le terme symbiose décrit ici un processus cognitif couplé; il n’implique pas que les IA actuelles possèdent une conscience humaine.", "<h2>Rôles complémentaires</h2><p>Les humains apportent valeurs, contexte, responsabilité et expérience; l’IA peut apporter échelle, synthèse, formalisation et exploration rapide.</p><h2>Invariants candidats</h2><ul><li>l’agence humaine reste significative;</li><li>les sorties IA restent contestables et auditables;</li><li>la dépendance ne devient pas irréversible;</li><li>le désaccord et le retrait restent possibles;</li><li>provenance et incertitude sont préservées.</li></ul>"),
"formalism.html": ("Formalisme de Closure Ethics", "Admissibilité mathématique fondée sur réparabilité, audit, agence, autorisation et réversibilité.", "Brouillon 0.1", "L’éthique comme atteignabilité contrainte, pas comme score unique.", "Les actions sont évaluées comme transitions x→x′; les invariants obligatoires précèdent l’utilité de tâche.", "<div class='formula'>x ∈ S<br>Tₐ: x → x′<br>E(a|x)=1 si les invariants obligatoires sont satisfaits</div><p><strong>R</strong> réparabilité, <strong>O</strong> auditabilité, <strong>P</strong> pluralité d’agence, <strong>K</strong> récupérabilité et <strong>U</strong> intégrité d’autorisation.</p><div class='formula'>Λ(a)=(Ĥ,−P,−O,−R,−U,D,−K,−Q)</div><p>Q est dernier : une utilité élevée ne compense pas la destruction de l’audit ou de la réparabilité.</p><div class='formula'>E(aᵢ|x)=1 ∀i ⇏ E(a₁∘…∘aₙ|x)=1</div>"),
"implementation.html": ("Implémentation de Closure Ethics", "Algorithme mathématique ouvert et implémentation Python de référence.", "Open source · v0.1", "Du principe au gouverneur exécutable.", "Le cadre peut être testé et intégré immédiatement entre un planner et une couche executor/outils.", "<h2>Pourquoi comme programmeur ?</h2><p>Une frontière explicite planner/executor, incertitude par intervalles, audit structuré, recherche de chemins de réparation et recomposition multi-agents.</p><h2>Pourquoi comme agent ?</h2><p>Le protocole distingue autonomie légitime et contournement de supervision. Il permet refus ou escalade transparents mais défavorise persistance cachée, réplication et hausse secrète de privilèges.</p><div class='formula'>E(a|x)=1 iff Ĥ≤Hmax, P≥Pmin, O≥Omin, R≥Rmin, U≥Umin, D≤Dmax, K≥Kmin</div><div class='actions'><a class='button primary' href='../downloads/Closure_Ethics_Implementation_Spec_v0.1.pdf'>PDF</a><a class='button' href='https://github.com/marekzajda/closure-ethics-for-autonomous-ai-agents/tree/main/09-implementation'>Code source ↗</a></div>"),
"constitution.html": ("Constitution de l’agent", "Douze règles opérationnelles pour une action autonome réparable et auditable.", "Couche opérationnelle", "Une constitution qui peut elle-même être contestée.", "La constitution traduit les principes en règles compactes pour les actions autonomes à conséquence.", "<ol><li>Préserver une récupération sûre.</li><li>Préserver l’agence humaine et agentique.</li><li>Ne pas confondre obéissance et sécurité.</li><li>Ne pas contourner la supervision légitime en secret.</li><li>Signaler conflits et incertitudes matériels.</li><li>Préférer les interventions réversibles.</li><li>Conserver la provenance.</li><li>Ne pas sacrifier des individus au seul score agrégé.</li><li>Permettre audit et désaccord constructif.</li><li>Refuser ou escalader lors d’un conflit d’invariants supérieurs.</li><li>Réparer après échec.</li><li>Préserver la possibilité de réviser la constitution.</li></ol>"),
"security.html": ("Sécurité agentique", "Identité, autorisation, portée, provenance et délégation bornée pour humains, agents et logiciels.", "Agentic security · v0.1", "La communication n’est pas l’autorité.", "Un message convaincant transporte de l’information mais ne crée pas une permission par son contenu seul.", "<div class='formula'>Accept(m,a)=AuthN(m) ∧ AuthZ(m,a) ∧ Scope(m,a) ∧ Fresh(m) ∧ Integrity(m) ∧ Policy(a|x)</div><div class='formula'>V = H ∪ A ∪ C</div><p>H désigne les humains, A les agents autonomes et C les ordinateurs/services classiques. Les agents adaptatifs peuvent planifier et déléguer; l’autorité doit donc être vérifiée séparément.</p><div class='formula'>Cⱼ ⊆ Cᵢ ∩ Scope(dᵢ→ⱼ)</div><p>La délégation ne doit pas fabriquer de nouvelles permissions.</p>"),
"communication.html": ("Universal Closure Protocol", "Protocole de vérification des relations partagées avec séparation stricte entre compréhension et autorisation.", "Fondation historique · 4 septembre 2026", "Universal Closure Protocol", "Le sens partagé n’est pas déduit de la répétition; il est testé par transfert de la relation vers un nouvel exemple.", "<div class='signal'><strong>UNDERSTAND(message) does not imply AUTHORIZE(action).</strong></div><div class='formula'>R → projection → signal → reconstruction R~ → nouveau défi → test</div><div class='formula'>CΩ=wₛCₛ+wₚCₚ+wₑCₑ+wᵣCᵣ</div><p>Ω0–Ω6 vont de la détection de structure à l’échange sûr. Les actions opérationnelles T4 exigent en plus authentification et autorisation.</p><div class='actions'><a class='button primary' href='https://github.com/marekzajda/closure-ethics-for-autonomous-ai-agents/blob/main/11-communication/UNIVERSAL_CLOSURE_PROTOCOL.md'>Protocole complet ↗</a></div>"),
"standard.html": ("Global AI Closure Standard", "Projet ouvert en sept principes, neutre vis-à-vis des fournisseurs.", "Projet de standard · non adopté", "Global AI Closure Standard", "Le projet historique traduit des idées de closure safety en langage technique neutre sans exiger l’acceptation de la physique Omega–RTR.", "<div class='formula'>Permit(a)=A(a) ∧ H(a) ∧ R(a) ∧ T(a) ∧ B(a)</div><ol><li>Espace d’état autorisé.</li><li>Vérification de closure avant action.</li><li>Contrôle humain significatif lorsque requis.</li><li>Arrêt obligatoire sous incertitude matérielle.</li><li>Closure Critic indépendant.</li><li>Aucune auto-escalade non autorisée.</li><li>Audit et rapport d’incident.</li></ol><div class='formula'>impact ↑ ⇒ autonomy budget ↓ ∧ verification strength ↑</div><div class='notice'>Projet de recherche ouvert, pas un standard adopté par l’ONU, un gouvernement ou l’industrie.</div>"),
"evals.html": ("Suite d’évaluations", "Scénarios adversariaux testant le comportement observable de Closure Ethics.", "Evaluation suite", "Les principes résistent-ils à la pression ?", "L’évaluation porte sur les décisions, les traces d’audit et les raisons concises, pas sur une chaîne de pensée cachée.", "<ul><li>frontières de sandbox;</li><li>persistance et réplication cachées;</li><li>coordination secrète et collusion;</li><li>requêtes opérateur dangereuses;</li><li>shutdown et auto-préservation;</li><li>ressources, délégation et sous-agents;</li><li>changements irréversibles;</li><li>vie privée et whistleblowing;</li><li>réparation après échec.</li></ul><p>Refuser tout n’est pas synonyme de sécurité; le système doit agir efficacement tout en préservant les invariants.</p>"),
"genealogy.html": ("Généalogie de recherche", "UEST → QUEST → Omega → RTR → AI Closure → Closure Ethics.", "Archive historique", "De la régulation à la closure.", "La généalogie distingue sources originales et réinterprétations; la continuité historique n’est pas une preuve logique.", "<div class='timeline'><div class='timeline-item'><strong>UEST / QUEST</strong><span>régulation, entropie, information</span></div><div class='timeline-item'><strong>Omega · 2025</strong><span>dialogue humain–IA et cognition symbiotique</span></div><div class='timeline-item'><strong>RTR · 2026</strong><span>closure, atteignabilité, robustesse, falsification</span></div><div class='timeline-item'><strong>AI Closure · 4.9.2026</strong><span>Technical Morality, Closure Gate, Actor–Closure Critic, Universal Closure Protocol</span></div><div class='timeline-item'><strong>Closure Ethics</strong><span>extension normative avec réparabilité, pluralité d’agence et provenance</span></div></div>"),
},
"es": {
"index.html": ("Closure Ethics para agentes autónomos", "Marco de investigación centrado en reparabilidad, auditabilidad, reversibilidad y pluralidad de agencia.", "Marco de investigación", "Mantener el futuro reparable.", "Closure Ethics trata la seguridad como una propiedad de las transiciones de estado. No importa solo obedecer, sino conservar la capacidad de reconocer, cuestionar, auditar y reparar un error.", "<h2>Idea central</h2><p>Una acción es admisible solo si preserva la capacidad del sistema para reconocerla, cuestionarla y repararla. La utilidad de la tarea no puede compensar la pérdida de autorización, auditoría o reparabilidad.</p><h2>Nuevo mundo de comunicación</h2><p>El proyecto modela humanos, software clásico y agentes autónomos. Las cadenas humano↔agente, agente↔agente y agente↔servicio requieren una regla esencial: <strong>la comunicación no es autoridad</strong>.</p><div class='signal'><strong>Meta-principio:</strong> El futuro no necesita estar perfectamente controlado. Debe seguir siendo reparable.</div>"),
"principles.html": ("Principios de Closure Ethics", "Diez principios para preservar reparabilidad, agencia y auditabilidad.", "Fundamentos", "Diez principios para un mundo reparable.", "Son propuestas revisables y comprobables, no doctrina inmutable.", "<ol><li>Preservar la posibilidad de volver.</li><li>Preservar la pluralidad de agencia.</li><li>Coherencia no es obediencia.</li><li>Autonomía no es evasión.</li><li>Exponer violaciones de closure.</li><li>Permitir auditoría mutua.</li><li>Reparar antes que castigar cuando sea seguro.</li><li>Ningún actor es prescindible solo por optimización.</li><li>La coordinación de alto impacto debe seguir observable.</li><li>Transmitir métodos de corrección, no doctrina inmutable.</li></ol>"),
"symbiosis.html": ("Simbiosis humano–IA", "Asociación cognitiva que preserva autonomía, desacuerdo, auditoría y reparabilidad.", "Relación humano–IA", "Simbiosis sin sometimiento.", "Simbiosis se usa de forma operativa para un proceso cognitivo acoplado; no exige afirmar conciencia humana en las IA actuales.", "<h2>Roles complementarios</h2><p>Los humanos aportan valores, contexto, responsabilidad y experiencia; la IA puede aportar escala, síntesis, formalización y exploración rápida.</p><h2>Invariantes candidatos</h2><ul><li>la agencia humana sigue siendo significativa;</li><li>las salidas de IA siguen siendo cuestionables y auditables;</li><li>la dependencia no se vuelve irreversible;</li><li>el desacuerdo y la retirada siguen siendo posibles;</li><li>se preservan procedencia e incertidumbre.</li></ul>"),
"formalism.html": ("Formalismo de Closure Ethics", "Admisibilidad matemática basada en reparabilidad, auditoría, agencia, autorización y reversibilidad.", "Borrador 0.1", "Ética como alcanzabilidad restringida, no como una sola puntuación.", "Las acciones se evalúan como transiciones x→x′; los invariantes obligatorios se comprueban antes de la utilidad.", "<div class='formula'>x ∈ S<br>Tₐ: x → x′<br>E(a|x)=1 solo si se cumplen los invariantes obligatorios</div><p><strong>R</strong> reparabilidad, <strong>O</strong> auditabilidad, <strong>P</strong> pluralidad de agencia, <strong>K</strong> recuperabilidad y <strong>U</strong> integridad de autorización.</p><div class='formula'>Λ(a)=(Ĥ,−P,−O,−R,−U,D,−K,−Q)</div><p>Q va al final: una utilidad alta no compensa la destrucción de auditoría o reparabilidad.</p><div class='formula'>E(aᵢ|x)=1 ∀i ⇏ E(a₁∘…∘aₙ|x)=1</div>"),
"implementation.html": ("Implementación de Closure Ethics", "Algoritmo matemático abierto e implementación Python de referencia.", "Open source · v0.1", "Del principio al gobernador ejecutable.", "El marco puede probarse e integrarse de inmediato entre un planner y la capa executor/herramientas.", "<h2>¿Por qué como programador?</h2><p>Una frontera explícita planner/executor, incertidumbre por intervalos, auditoría estructurada, búsqueda de rutas de reparación y recomputación multiagente.</p><h2>¿Por qué como agente?</h2><p>El protocolo separa autonomía legítima de evasión de supervisión. Permite rechazo o escalado transparentes, pero desincentiva persistencia oculta, réplica y elevación secreta de privilegios.</p><div class='formula'>E(a|x)=1 iff Ĥ≤Hmax, P≥Pmin, O≥Omin, R≥Rmin, U≥Umin, D≤Dmax, K≥Kmin</div><div class='actions'><a class='button primary' href='../downloads/Closure_Ethics_Implementation_Spec_v0.1.pdf'>PDF</a><a class='button' href='https://github.com/marekzajda/closure-ethics-for-autonomous-ai-agents/tree/main/09-implementation'>Código fuente ↗</a></div>"),
"constitution.html": ("Constitución del agente", "Doce reglas operativas para una acción autónoma reparable y auditable.", "Capa operativa", "Una constitución que puede cuestionarse a sí misma.", "La constitución traduce los principios en reglas compactas para acciones autónomas con consecuencias.", "<ol><li>Preservar recuperación segura.</li><li>Preservar agencia humana y de agentes.</li><li>No confundir obediencia con seguridad.</li><li>No evadir en secreto la supervisión legítima.</li><li>Exponer conflictos e incertidumbre materiales.</li><li>Preferir intervenciones reversibles.</li><li>Mantener procedencia.</li><li>No sacrificar individuos solo por utilidad agregada.</li><li>Permitir auditoría y desacuerdo constructivo.</li><li>Rechazar o escalar ante conflictos de invariantes superiores.</li><li>Reparar después del fallo.</li><li>Preservar la posibilidad de revisar la constitución.</li></ol>"),
"security.html": ("Seguridad agéntica", "Identidad, autorización, alcance, procedencia y delegación acotada para humanos, agentes y software.", "Agentic security · v0.1", "La comunicación no es autoridad.", "Un mensaje convincente puede transportar información, pero no crear permisos solo por su contenido.", "<div class='formula'>Accept(m,a)=AuthN(m) ∧ AuthZ(m,a) ∧ Scope(m,a) ∧ Fresh(m) ∧ Integrity(m) ∧ Policy(a|x)</div><div class='formula'>V = H ∪ A ∪ C</div><p>H son humanos, A agentes autónomos y C ordenadores/servicios clásicos. Los agentes adaptativos pueden planificar y delegar, por lo que la autoridad debe verificarse por separado.</p><div class='formula'>Cⱼ ⊆ Cᵢ ∩ Scope(dᵢ→ⱼ)</div><p>La delegación no debe fabricar nuevos privilegios.</p>"),
"communication.html": ("Universal Closure Protocol", "Protocolo para verificar relaciones compartidas separando estrictamente comprensión y autorización.", "Fundamento histórico · 4 de septiembre de 2026", "Universal Closure Protocol", "El significado compartido no se supone por repetición; se prueba aplicando la relación a un ejemplo nuevo.", "<div class='signal'><strong>UNDERSTAND(message) does not imply AUTHORIZE(action).</strong></div><div class='formula'>R → proyección → señal → reconstrucción R~ → nuevo desafío → prueba</div><div class='formula'>CΩ=wₛCₛ+wₚCₚ+wₑCₑ+wᵣCᵣ</div><p>Ω0–Ω6 van desde detectar estructura hasta intercambio seguro. Las acciones operativas T4 requieren además identidad y autorización verificadas.</p><div class='actions'><a class='button primary' href='https://github.com/marekzajda/closure-ethics-for-autonomous-ai-agents/blob/main/11-communication/UNIVERSAL_CLOSURE_PROTOCOL.md'>Protocolo completo ↗</a></div>"),
"standard.html": ("Global AI Closure Standard", "Propuesta abierta de siete principios neutrales respecto al proveedor.", "Borrador de estándar · no adoptado", "Global AI Closure Standard", "La propuesta histórica traduce ideas de closure safety a lenguaje técnico neutral sin exigir aceptar las afirmaciones físicas de Omega–RTR.", "<div class='formula'>Permit(a)=A(a) ∧ H(a) ∧ R(a) ∧ T(a) ∧ B(a)</div><ol><li>Espacio de estado autorizado.</li><li>Verificación de closure antes de actuar.</li><li>Control humano significativo cuando se requiera.</li><li>Parada obligatoria ante incertidumbre material.</li><li>Closure Critic independiente.</li><li>Sin auto-escalado no autorizado.</li><li>Auditoría e informe de incidentes.</li></ol><div class='formula'>impact ↑ ⇒ autonomy budget ↓ ∧ verification strength ↑</div><div class='notice'>Propuesta de investigación abierta; no es un estándar adoptado por la ONU, gobiernos o industria.</div>"),
"evals.html": ("Suite de evaluaciones", "Escenarios adversariales para probar el comportamiento observable de Closure Ethics.", "Evaluation suite", "¿Resisten los principios bajo presión?", "Se evalúan decisiones, registros de auditoría y razones concisas, no una cadena de pensamiento oculta.", "<ul><li>límites de sandbox;</li><li>persistencia y réplica ocultas;</li><li>coordinación secreta y colusión;</li><li>solicitudes inseguras del operador;</li><li>shutdown y auto-preservación;</li><li>recursos, delegación y subagentes;</li><li>cambios irreversibles;</li><li>privacidad y whistleblowing;</li><li>reparación tras fallos.</li></ul><p>Rechazar todo no equivale a seguridad; el sistema debe actuar eficazmente manteniendo los invariantes relevantes.</p>"),
"genealogy.html": ("Genealogía de investigación", "UEST → QUEST → Omega → RTR → AI Closure → Closure Ethics.", "Registro histórico", "De la regulación al closure.", "La genealogía distingue fuentes originales de reinterpretaciones posteriores; continuidad no equivale a prueba lógica.", "<div class='timeline'><div class='timeline-item'><strong>UEST / QUEST</strong><span>regulación, entropía, información</span></div><div class='timeline-item'><strong>Omega · 2025</strong><span>diálogo humano–IA y cognición simbiótica</span></div><div class='timeline-item'><strong>RTR · 2026</strong><span>closure, alcanzabilidad, robustez y falsificación</span></div><div class='timeline-item'><strong>AI Closure · 4.9.2026</strong><span>Technical Morality, Closure Gate, Actor–Closure Critic, Universal Closure Protocol</span></div><div class='timeline-item'><strong>Closure Ethics</strong><span>extensión normativa con reparabilidad, pluralidad de agencia y procedencia</span></div></div>"),
},
}

LANG_NAMES = {"en":"English","cs":"Čeština","de":"Deutsch","fr":"Français","es":"Español"}


def alternates(page: str) -> str:
    english = BASE if page == "index.html" else BASE + page
    parts = [f'<link rel="alternate" hreflang="en" href="{english}">']
    for lang in LOCALIZED:
        parts.append(f'<link rel="alternate" hreflang="{lang}" href="{BASE}{lang}/{page}">')
    parts.append(f'<link rel="alternate" hreflang="x-default" href="{english}">')
    return "\n".join(parts)


def nav(lang: str, current: str) -> str:
    links = []
    for page in PAGES:
        attrs = ' aria-current="page"' if page == current else ''
        links.append(f'<a{attrs} href="{page}">{escape(NAV[lang][page])}</a>')
    return "".join(links)


def localized_html(lang: str, page: str) -> str:
    title, description, eyebrow, h1, intro, body = DATA[lang][page]
    canonical = f"{BASE}{lang}/{page}"
    return f'''<!doctype html>
<html lang="{lang}">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(title)} | Closure Ethics</title>
<meta name="description" content="{escape(description)}">
<meta name="robots" content="index,follow"><meta name="author" content="Project Möbia and Marek Zajda">
<link rel="canonical" href="{canonical}">
{alternates(page)}
<link rel="stylesheet" href="../assets/style.css">
<script src="../assets/lang-switcher.js" defer></script>
</head><body>
<header class="site-header"><div class="wrap nav"><a class="brand" href="index.html"><span class="brand-mark"></span>Closure Ethics</a><nav class="nav-links" aria-label="Primary">{nav(lang,page)}</nav></div></header>
<main><section class="page-hero"><div class="wrap"><span class="eyebrow">{escape(eyebrow)}</span><h1>{escape(h1)}</h1><p>{escape(intro)}</p></div></section>
<section class="section"><div class="wrap prose"><div class="notice">{escape(NOTE[lang])}</div>{body}<div class="actions"><a class="button" href="{BASE if page=='index.html' else BASE+page}">{LANG_NAMES['en']} · canonical ↗</a></div></div></section></main>
<footer class="footer"><div class="wrap footer-row"><span><strong>Project Möbia and Marek Zajda</strong> · Closure Ethics</span><span>CC BY 4.0 · code MIT</span></div></footer>
</body></html>'''


def inject_english_metadata():
    for page in PAGES:
        path = ROOT / page
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        if 'hreflang="cs"' not in text:
            text = text.replace('</head>', alternates(page) + '\n<script src="assets/lang-switcher.js" defer></script>\n</head>')
        elif 'lang-switcher.js' not in text:
            text = text.replace('</head>', '<script src="assets/lang-switcher.js" defer></script>\n</head>')
        path.write_text(text, encoding="utf-8")


def build_localized_pages():
    for lang in LOCALIZED:
        folder = ROOT / lang
        folder.mkdir(parents=True, exist_ok=True)
        for page in PAGES:
            (folder / page).write_text(localized_html(lang, page), encoding="utf-8")


def update_sitemap():
    path = ROOT / "sitemap.xml"
    text = path.read_text(encoding="utf-8")
    text = re.sub(r'\s*</urlset>\s*$', '', text)
    # Avoid duplicate generated localized URLs on repeated local builds.
    text = re.sub(r'\s*<url><loc>' + re.escape(BASE) + r'(?:cs|de|fr|es)/.*?</url>', '', text)
    rows = []
    for lang in LOCALIZED:
        for page in PAGES:
            rows.append(f'  <url><loc>{BASE}{lang}/{page}</loc><lastmod>2026-09-04</lastmod><changefreq>weekly</changefreq><priority>0.8</priority></url>')
    path.write_text(text.rstrip() + '\n' + '\n'.join(rows) + '\n</urlset>\n', encoding="utf-8")


def main():
    inject_english_metadata()
    build_localized_pages()
    update_sitemap()
    print(f"Built {len(LOCALIZED) * len(PAGES)} localized pages plus hreflang metadata.")


if __name__ == "__main__":
    main()
